# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array=np.array([32,45,67,89,12])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(array))

[12 32 45 67 89]


# Problem 2

In [17]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

sayılar=np.array([10,15,30,45,60])
print(sayılar)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
sayılar2 =np.arange(5,15)
print(sayılar2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
sayılar3 = np.arange(50,100,5)
print(sayılar3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
sayılar4=np.zeros(10)
print(sayılar4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
sayılar5=np.ones(10)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
sayılar6=np.linspace(0,100,5)
print(sayılar6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

random_numbers=np.random.randint(10,31,size=5)
print(random_numbers)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
random_numbers2=np.random.uniform(-1,1,size=10)
print(random_numbers2)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
random_numbers3 = np.random.randint(10,50,size=(3,5))
print(random_numbers3)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(random_numbers3.sum(axis=0))
print(random_numbers3.sum(axis=1))
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

print(random_numbers3.max())
print(random_numbers3.min())
print(random_numbers3.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?

print(random_numbers3.argmax())
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

random_numbers4= np.random.randint(10,20,size=8)
print(random_numbers4[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(random_numbers4[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(random_numbers3[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(random_numbers3[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(random_numbers3[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.

print(random_numbers3*2)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
random_numbers5= np.random.randint(-50,50,size=(3,5))
print((random_numbers5>0) & (random_numbers5 % 2 == 0))

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[  0.  25.  50.  75. 100.]
[18 26 23 26 19]
[ 0.49891115  0.00091026  0.36262996 -0.63807633  0.87538138  0.44239568
 -0.78860836  0.02827141  0.30433811 -0.90243973]
[[44 15 36 27 47]
 [29 43 21 29 44]
 [31 11 37 43 23]]
[104  69  94  99 114]
[169 166 145]
47
11
32.0
4
[16 11 10]
[14 11 13 19 15 10 11 16]
[44 15 36 27 47]
21
[44 29 31]
[[88 30 72 54 94]
 [58 86 42 58 88]
 [62 22 74 86 46]]
[[False False False False  True]
 [False  True False False  True]
 [False False False False False]]
