# Problem 1

In [1]:
pip install numpy

     ---------------------------------------- 14.8/14.8 MB 5.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
import numpy as np
matris = np.random.randint(0, 11, size=(5, 5))

print(matris)

# 3 - matris'in boyutunu öğrenin
print(matris.shape)

# 4 - matris'i yeniden boyutlandırın
yeniden = matris.reshape(25, 1)
print(yeniden)

# 5 - matris'in boyut sayısını öğrenin
print(matris.ndim)

[[ 9  2 10  8  0]
 [ 5  1  3  7  1]
 [ 8  1  9  5  6]
 [ 3  4  8  7  1]
 [ 1  2  2  0  8]]
(5, 5)
[[ 9]
 [ 2]
 [10]
 [ 8]
 [ 0]
 [ 5]
 [ 1]
 [ 3]
 [ 7]
 [ 1]
 [ 8]
 [ 1]
 [ 9]
 [ 5]
 [ 6]
 [ 3]
 [ 4]
 [ 8]
 [ 7]
 [ 1]
 [ 1]
 [ 2]
 [ 2]
 [ 0]
 [ 8]]
2


# Problem 2

In [3]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
import numpy as np
matris = np.random.randint(1, 11, size=(3, 3))
matris = matris[matris % 2 == 1]
print(matris)

# 2 - Oluşturduğunuz matrisi parçalayın
bloklar = [matris[i:i+2, j:j+2] for i in range(0, 5, 2) for j in range(0, 5, 2)]

for i, blok in enumerate(bloklar):
    print(f"Blok {i}:")
    print(blok)

# 3 - Parçalanmış matrisleri birleştirin
birlesik_matris = np.concatenate([np.concatenate(bloklar[:2], axis=1), 
                                   np.concatenate(bloklar[2:], axis=1)], axis=0)

# birleştirilmiş matrisi yazdırma
print("Birleştirilmiş Matris:")
print(birlesik_matris)


[5 7 7 7 5 1 7 3]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

# Problem 3

In [8]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
import numpy as np


sayilar = np.arange(5, 101, 2)


rastgele_sayilar = np.random.choice(sayilar, size=10, replace=False)


matris = rastgele_sayilar.reshape(5, 2)


print(matris)

# 2 - matris'in özelliklerini inceleyin
print(matris.shape)
print(matris.size)
print(matris.dtype)


[[35 53]
 [79 21]
 [67 43]
 [23 99]
 [ 5 95]]
(5, 2)
10
int32
